--vypíše všechny položky z originální tabulky v netransformované podobì, použije sloupce IDS, Nazev

SELECT TOP (1000)[IDS]
      ,[Nazev]
      ,[SText]
      ,[MJ]
      ,[StavZ]
      ,[MinLim]
      ,[MinMax]
      ,[Hmotnost]
      ,[NakupC]
      ,[NakupDPH]
      ,[NakupCM]
      ,[CMKodNC]
      ,[VNakup]
      ,[ProdejKc]
      ,[ProdejDPH]
      ,[Marze]
      ,[Rabat]
      ,[ObjMn]
      ,[ObjNazev]
      ,[RefAD]
      ,[Firma]
      ,[PLU]
      ,[Popis2]
      ,[DatCreate]
      ,[DatSave]
      ,[Oznacil]
      ,[Ucetni]
      ,[Creator]
  FROM [StwPh_27538117].[dbo].[SKz]
